In [ ]:
import Fibo

In [ ]:
retun a-b

SyntaxError: invalid syntax (<ipython-input-2-583ad99acdd2>, line 1)

In [ ]:
Fibo.fib(100)

0
1
1
2
3
5
8
13
21
34
55
89


In [ ]:
import num

In [ ]:
num.sub(100,1)

99

In [ ]:
num.sum(100,1)

101

In [ ]:
from Fibo import fib

In [ ]:
Fibo.fib(100)

0
1
1
2
3
5
8
13
21
34
55
89


In [ ]:
fib.fib(100)

AttributeError: 'function' object has no attribute 'fib'

In [ ]:
import Fibo as fib

In [ ]:
fib.fib(100)

0
1
1
2
3
5
8
13
21
34
55
89


In [ ]:
#module directory bhitra gayera khojcha

In [ ]:
dir(fib)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'fib',
 'fib2']

In [ ]:
#dir le yo file bhitra k k cha vanera

In [ ]:
#first library that we use is numpy

In [ ]:
#numpy for numericals, pandas for visualization, matplot, seaborn for graph

In [ ]:
#install numpy, pandas, matplotlib using pip install

In [ ]:
#numpy alias is np

In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.1.0'

In [ ]:
# numpy is np, pandas is pd, matplot is plt

In [ ]:
# numpy arrays are list but are more efficient storage and operations on data than python lists

In [ ]:
my_arr = np.array([2,4,8,16])

In [ ]:
# numpy ko input sabai array mei kaam garcha not in list

In [ ]:
my_arr

array([ 2,  4,  8, 16])

In [ ]:
type(my_arr)

numpy.ndarray

In [ ]:
np.array([1, 2.4, 3, 4, 5])

array([1. , 2.4, 3. , 4. , 5. ])

In [ ]:
# everything on float, only takes one data type and changes type forcefully to the more storage one

In [ ]:
np.array(['string', 1, 2.0])

array(['string', '1', '2.0'], dtype='<U32')

In [ ]:
# dtype='<U32' string type is universal 32 bit

In [ ]:
np.array([1, 2, 3, 3.5], dtype="int16")

array([1, 2, 3, 3], dtype=int16)

In [ ]:
#forcefully int ma lageko with dtype

In [ ]:
#multi-dimensional array

In [ ]:
np.array(
    [
        # 3 by 3 array
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.zeros(5, dtype='int')

array([0, 0, 0, 0, 0])

In [ ]:
#here x,y,z huncha
np.ones((3, 5, 2), dtype=float)

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
np.arange(1, 31, 3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [ ]:
#python ko range, numpy ko arange

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# linear spacing

In [ ]:
# numpy standard data types check in notes