In [ ]:
import numpy as np

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(4, 3))
x3 = np.random.randint(10, size=(2, 3, 4))
x1

array([0, 0, 7, 1, 5, 9], dtype=int32)

In [ ]:
# ndim = no. of dimensions?

In [ ]:
print(x1.ndim)

1


In [ ]:
print(x2.ndim)

2


In [ ]:
print(x3.ndim)

3


In [ ]:
#shape = size of each dimension (v .imp)

In [ ]:
print(x1.shape)
print(x2.shape)
print(x3.shape)

(6,)
(4, 3)
(2, 3, 4)


In [ ]:
# size = how many elements in total

In [ ]:
print(x1.size)
print(x2.size)
print(x3.size)

6
12
24


In [ ]:
# shape and size is the first step in DS mostly

In [ ]:
x1.dtype

dtype('int32')

In [ ]:
# x1 is an array which has int. x1 associated with numpy

In [ ]:
print("x2.itemsize =", x2.itemsize)
print("x2.nbytes=", x2.nbytes)

x2.itemsize = 4
x2.nbytes= 48


In [ ]:
print(x1)
print(x1[0])

[0 0 7 1 5 9]
0


In [ ]:
print(x2)

[[5 0 0]
 [1 7 7]
 [7 2 7]
 [1 9 8]]


In [ ]:
print("item at 3rd row and 2nd column is", x2[2, 1])

item at 3rd row and 2nd column is 2


In [ ]:
print("item at 3rd row and last column is", x2[2, -1])

item at 3rd row and last column is 7


In [ ]:
x2[2, -1] = 3.1415
print(x2)
print("Updated = ", x2[2, -1])

[[5 0 0]
 [1 7 7]
 [7 2 3]
 [1 9 8]]
Updated =  3


In [ ]:
x = np.arange(10)

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#slicing

In [ ]:
x[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
x[3:8]

array([3, 4, 5, 6, 7])

In [ ]:
x[::2]

array([0, 2, 4, 6, 8])

In [ ]:
x[2::2]

array([2, 4, 6, 8])

In [ ]:
x[7:3:-1] #index 7 to index 4 decrement by 1

array([7, 6, 5, 4])

In [ ]:
x[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x2

array([[5, 0, 0],
       [1, 7, 7],
       [7, 2, 3],
       [1, 9, 8]], dtype=int32)

In [ ]:
x2[:3, :2]  # rows = index 0 to 2, columns = index 0 to 1

array([[5, 0],
       [1, 7],
       [7, 2]], dtype=int32)

In [ ]:
x2[::2, :]  # every other 2 rows, all columns

array([[5, 0, 0],
       [7, 2, 3]], dtype=int32)

In [ ]:
x2[::-1, ::-1]

array([[8, 9, 1],
       [3, 2, 7],
       [7, 7, 1],
       [0, 0, 5]], dtype=int32)

In [ ]:
x2[:, 1]

array([0, 7, 2, 9], dtype=int32)

In [ ]:
# reshaping arrays

In [ ]:
z = np.arange(1, 10)

In [ ]:
z

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
z.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
z.reshape((4, 4))

ValueError: cannot reshape array of size 9 into shape (4,4)

In [ ]:
# array concatenation and spliting

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
np.concatenate([arr2d, arr2d])  # by default rpws ma huncha i.e. x=0

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
np.concatenate([arr2d, arr2d], axis=1)  # axis 1 vaneko columns

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
# horizontal and vertical add is hstack and vstack

In [ ]:
np.vstack([x, arr2d])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
# do hstack yourself at home

In [ ]:
# splitting arrays

In [ ]:
x = [1, 2, 3, 4, 5, 6, 7, 8]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [4 5] [6 7 8]


In [ ]:
# do hsplit and vsplit at home

In [ ]:
# check how much time it took for operation %timeit check in pdf at home

In [ ]:
x = np.array([-2, -3, 10, -1])

In [ ]:
np.abs(x)

array([ 2,  3, 10,  1])

In [ ]:
theta = np.linspace(0, np.pi, 3)

In [ ]:
theta

array([0.        , 1.57079633, 3.14159265])

In [ ]:
print("sin(theta) =", np.sin(theta))

sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [ ]:
# linspace is linear spacing so pi is 180 degree so 0 to 180 ko three spaces lincha