In [ ]:
import pandas as pd
import numpy as np

rng = np.random.RandomState(42)
A = pd.DataFrame(rng.randint(0, 20, (2, 2)), columns=list("AB"))
print(A)

    A   B
0   6  19
1  14  10


In [ ]:
B = pd.DataFrame(rng.randint(0, 10, (2, 3)), columns=list("BAC"))
print(B)

   B  A  C
0  7  4  3
1  7  7  2


In [ ]:
A + B

A   B   C
0  10  26 NaN
1  21  17 NaN

In [ ]:
A.add(B, fill_value=0)

A   B    C
0  10  26  3.0
1  21  17  2.0

In [ ]:
A - A.iloc[0]

A  B
0  0  0
1  8 -9

In [ ]:
A = rng.randint(10, size=(3, 4))
A

array([[5, 4, 1, 7],
       [5, 1, 4, 0],
       [9, 5, 8, 0]], dtype=int32)

In [ ]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 0, -3,  3, -7],
       [ 4,  1,  7, -7]], dtype=int32)

In [ ]:
df = pd.DataFrame(A, columns=list("QRST"))
df

Q  R  S  T
0  5  4  1  7
1  5  1  4  0
2  9  5  8  0

In [ ]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  0 -3  3 -7
2  4  1  7 -7

In [ ]:
# nan safe mode

In [ ]:
# Dealing with missing values in python ( NaN(np ko) values and None (pythonko) object)

In [ ]:
vals1 = np.array([1, None, 2, 3])
vals1

array([1, None, 2, 3], dtype=object)

In [ ]:
Vals2 = np.array([1, np.nan, 2, 3])
Vals2

array([ 1., nan,  2.,  3.])

In [ ]:
Vals2.sum()

np.float64(nan)

In [ ]:
np.nansum(Vals2)

np.float64(6.0)

In [ ]:
# nansum ignores nan values - it's the safe mode

In [ ]:
np.nanmax(vals1)

TypeError: '>=' not supported between instances of 'int' and 'NoneType'

In [ ]:
np.nanmax(Vals2)

np.float64(3.0)

In [ ]:
data = pd.Series([1, np.nan, "hello", None])

In [ ]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [ ]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [ ]:
data.isnull(sum)

TypeError: Series.isnull() takes 1 positional argument but 2 were given

In [ ]:
data.isnull().sum()

np.int64(2)

In [ ]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [ ]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [ ]:
data.dropna()  # drop not available

0        1
2    hello
dtype: object

In [ ]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [ ]:
data.dropna(inplace=True)

In [ ]:
data

0        1
2    hello
dtype: object

In [ ]:
data.reset_index()

index      0
0      0      1
1      2  hello

In [ ]:
# reset index

In [ ]:
df = pd.DataFrame([[1, 2, np.nan], [2, 3, 4], [5, 6, np.nan]])
df

0  1    2
0  1  2  NaN
1  2  3  4.0
2  5  6  NaN

In [ ]:
df.dropna()

0  1    2
1  2  3  4.0

In [ ]:
# dropna le row nei hatayo

In [ ]:
df.drop(axis=1)

ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [ ]:
df.dropna(axis=1)

0  1
0  1  2
1  2  3
2  5  6

In [ ]:
df1 = pd.DataFrame([[1, 2, np.nan], [2, 3, 4], [np.nan, 6, 5]])
df1
df1.dropna(axis="columns")

1
0  2
1  3
2  6

In [ ]:
df[3] = np.nan

In [ ]:
df

0  1    2   3
0  1  2  NaN NaN
1  2  3  4.0 NaN
2  5  6  NaN NaN

In [ ]:
df.dropna(axis="columns", how="all")

0  1    2
0  1  2  NaN
1  2  3  4.0
2  5  6  NaN

In [ ]:
# sabai value NaN cha vaney chai drop gardincha

In [ ]:
df.dropna(axis="rows", thresh=2)

0  1    2   3
0  1  2  NaN NaN
1  2  3  4.0 NaN
2  5  6  NaN NaN

In [ ]:
df.dropna(axis="rows", thresh=3)  # keep roles with a minimum of 3 non-null values

0  1    2   3
1  2  3  4.0 NaN

In [ ]:
df.fillna(0)

0  1    2    3
0  1  2  0.0  0.0
1  2  3  4.0  0.0
2  5  6  0.0  0.0

In [ ]:
df.fillna(5)

0  1    2    3
0  1  2  5.0  5.0
1  2  3  4.0  5.0
2  5  6  5.0  5.0

In [ ]:
df.fillna(method='ffill')

<ipython-input-59-5c0beae7dc1e>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')


0  1    2   3
0  1  2  NaN NaN
1  2  3  4.0 NaN
2  5  6  4.0 NaN